name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Validate Gradle Wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Set up JDK 17
      uses: actions/setup-java@v3.11.0
      with:
        distribution: 'zulu'
        java-version: 17

    - name: Setup gradle
      uses: gradle/gradle-build-action@v2

    - name: Execute a build
      run: ./gradlew build :sample-plugin:buildPlugin --stacktrace

    - name: Verify plugin on IntelliJ Platforms
      id: verify
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
      with:
        plugin-location: sample-plugin/build/distributions/*.zip
        ide-versions: |
          ideaIC:2021.1
          ideaIU:2021.1

    - name: Get log file path and print contents
      if: failure()
      run: |
        echo "The log file path is: ${{steps.verify.outputs.verification-output-log-filename}}" ;
        cat ${{steps.verify.outputs.verification-output-log-filename}}

env:
  GRADLE_OPTS: -Dorg.gradle.configureondemand=true -Dorg.gradle.parallel=true -Dkotlin.incremental=false -Dorg.gradle.jvmargs="-Xmx3g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8"
